
clear; clc; close all;
addpath('utils')

%specifying inputs
target_train_name = 'spike_train_ex1'; % spike trains to fit network model to. Here we use a spike train generated by a spatial balanced network as an example. 
simulator = @(input_para,T)SBN(input_para,T); % function handle to the network model
parameter_range = [1,140]; % range of parameters, here we are fitting JrEx, feedforward excitatory connection strength
max_iter = 6; % stopping criterion (in iterations)
T = 50000; % network model simulation length (in ms)
Ne = 2500; % number of E neurons in the read-out layer of the model to be fitted
save_name = 'ex1'; % name of the log file for optimization. You can find it under the data folder. ex1.mat contains optimization information, ex1_stats.mat contains the activity statistics of each iteration.
is_plot=0; % if illustrative plot is needed. If turned off, fitting information will be printed in the stout

%running the fitting algorithm
SNOPS(target_train_name,simulator,parameter_range,max_iter,T,Ne,save_name,is_plot);
